# ДЗ 1. Анализ данных о зарплатах преподавателей старшей школы

## Винник Екатерина Петровна, 22.М04

    library(readr)

    school_earnings <- read_csv("data/school_earnings.csv")

    ## Rows: 21 Columns: 4
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): School
    ## dbl (3): Women, Men, Gap
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    print(school_earnings)

    ## # A tibble: 21 × 4
    ##    School     Women   Men   Gap
    ##    <chr>      <dbl> <dbl> <dbl>
    ##  1 MIT           94   152    58
    ##  2 Stanford      96   151    55
    ##  3 Harvard      112   165    53
    ##  4 U.Penn        92   141    49
    ##  5 Princeton     90   137    47
    ##  6 Chicago       78   118    40
    ##  7 Georgetown    94   131    37
    ##  8 Tufts         76   112    36
    ##  9 Yale          79   114    35
    ## 10 Columbia      86   119    33
    ## # ℹ 11 more rows

## Численное описание данных

    library(dplyr)

    ## 
    ## Присоединяю пакет: 'dplyr'

    ## Следующие объекты скрыты от 'package:stats':
    ## 
    ##     filter, lag

    ## Следующие объекты скрыты от 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

    print("Данные по зарплате у женщин")

    ## [1] "Данные по зарплате у женщин"

    summary(school_earnings$Women)

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##    62.0    72.0    79.0    81.1    92.0   112.0

    summarise(school_earnings,  "Минимум"=min(Women), "Медиана"=median(Women), "Среднее"=mean(Women), "Максимум"=max(Women))

    ## # A tibble: 1 × 4
    ##   Минимум Медиана Среднее Максимум
    ##     <dbl>   <dbl>   <dbl>    <dbl>
    ## 1      62      79    81.1      112

Таким образом, можно заключить, что:

-   минимум зарплаты у женщин составляет 62, максимум – 112, т.е.,
    максимальная зарплата почти в два раза больше минимальной;
-   медианная зарплата у женщин составляет 79, средняя – 81;
-   медиана находится ближе к минимуму зарплаты, чем к максимуму, из
    этого можно отметить, что половина значений зарплат женщин находится
    в пределах от 62 до 79, а вторая половина значений зарплат
    рассредоточена на более широком диапазоне – от 79 до 112.

<!-- -->

    ("Данные по зарплате у мужчин")

    ## [1] "Данные по зарплате у мужчин"

    summary(school_earnings$Men)

    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##    78.0    92.0   114.0   113.5   131.0   165.0

    summarise(school_earnings,  "Минимум"=min(Men), "Медиана"=median(Men), "Среднее"=mean(Men), "Максимум"=max(Men))

    ## # A tibble: 1 × 4
    ##   Минимум Медиана Среднее Максимум
    ##     <dbl>   <dbl>   <dbl>    <dbl>
    ## 1      78     114    114.      165

Таким образом, можно заключить, что:

-   минимум зарплаты у мужчин составляет 78, максимум – 165.
-   медианная зарплата у мужчин составляет 114, средняя превышает 113.5.
-   размер зарплаты среди мужчин превосходит размер зарплаты среди
    женщин по каждому из измерений: минимальной зарплате, медиане,
    среднему и максимальной зарплате;
-   значение максимальной зарплаты среди мужчин более чем в два раза
    превышает значение минимальной зарплаты среди мужчин.

## График с усами

Рассмотрим график с усами, иллюстрирующий множество значений зарплат
женщин.

    boxplot(school_earnings$Women)

![](Vinnik-hw1_files/figure-markdown_strict/women%20boxplot-1.png)

На графике видно, что:

-   минимальное значение зарплаты женщины немного превышает 60 (из
    результата функции summary известно, что это 62), а максимальное
    немного превышает 110 (составляет 112).
-   медианное значение составляет немного меньше 80 (из результата
    функции summary известно, что это 79).
-   значение первого квантиля немного превышает 70 (из результата
    функции summary известно, что это 72) – то есть, 25% зарплат
    находится в пределах от 62 до 72.
-   значение третьего квантиля немного превышает 90 (из результата
    функции summary известно, что это 92) – то есть, 75% зарплат
    находится в пределах от 62 до 92.

Можно заключить, что значения характеристик зарплат женщин,
демонстрируемые графиком, согласуются со значениями, полученными с
помощью функций summary, summarise.

Рассмотрим график с усами, иллюстрирующий множество значений зарплат
мужчин:

    boxplot(school_earnings$Men)

![](Vinnik-hw1_files/figure-markdown_strict/men%20boxplot-1.png)

На графике видно, что:

-   минимальное значение зарплаты мужчины немного меньше 80 (из
    результата функции summary известно, что это 78), а максимальное
    превышает 160 (составляет 165).
-   медианное значение составляет немного меньше 120 (из результата
    функции summary известно, что это 114).
-   значение первого квантиля находится между 80 и 100 (из результата
    функции summary известно, что это 92) – то есть, 25% зарплат мужчин
    находится в пределах от 78 до 92.
-   значение третьего квантиля находится между 120 и 140 (из результата
    функции summary известно, что это 131) – то есть, 75% зарплат
    находится в пределах от 78 до 131.

Можно заключить, что значения характеристик зарплат мужчин,
демонстрируемые графиком, согласуются со значениями, полученными с
помощью функций `summary`, `summarise`.
